export enum AccountTypes {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  COMMISSINER = "COMMISSINER",
  SECRETARY = "SECRETARY",
  STAFF = "STAFF",
  USER = "USER",
}

export enum AccountRoles {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  COMMISSINER = "COMMISSINER",
  SECRETARY = "SECRETARY",
  STAFF = "STAFF",
  USER = "USER",
}

export enum TownUnionOffices {
  TRADITIONAL_RULER = "TRADITIONAL_RULER",
  PRIME_MINISTER = "PRIME_MINISTER",
  PRESIDENT = "PRESIDENT",
  LEGAL_ADVISER = "LEGAL_ADVISER",
  VICE_PRESIDENT = "VICE_PRESIDENT",
  TREASURER = "TREASURER",
  SECRETARY_GENERAL = "SECRETARY_GENERAL",
  FINANCIAL_SECRETARY = "FINANCIAL_SECRETARY",
  PUBLICITY_SECRETARY = "PUBLICITY_SECRETARY",
  PROVOST_I = "PROVOST_I",
  PROVOST_II = "PROVOST_II",
  ASSISTANT_SECRETARY = "ASSISTANT_SECRETARY",
  DELEGATE = "DELEGATE",
  MEMBER = "MEMBER",
}
